### ISSUE TITLE
Make program robust against deviations in input files

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/morphometricanalyzer#41]
In the process of preparing suitable and realistic example files for user I noticed that the program is rather "unstable" when there are small inconsistencies or variations in the way the data are included in the input files. I came across two issues which can be illustrated with the attached files.

- "examplefile1": with my example file that contains three species, the program crashes, but if I reduce to two species, the modified version works. Probably the problem is due to the lack of one sex or otherwise an imbalance of categories in the main example file. In such a case, it would be good if the program proceeds and continues doing those calculations it can perform, and just skips the ones that are not possible.

- "examplefile2". This is a larger realistic data set with real data, and it causes the program to crash. I wondered what could be the reason and then realized it was the presence of strange characters in the specimenid column. When I simplified those, the modified input file works. Also here it would be good to find a solution: as a minimum, give an informative error message when problematic characters, missing data etc. are found in one of the columns. Or better, simply replace all problematic characters by underscores before starting the analysis. 

[examplefiles_Morphometricanalyzer.zip](https://github.com/iTaxoTools/morphometricanalyzer/files/6526903/examplefiles_Morphometricanalyzer.zip)

**Comment by necrosovereign** [comment]
I found out the exact reasons why these files crash the program

- "examplefile1" has several specimens with the same specimenid. When the program tries to read the value of a variable for this specimenid, it gets multiple values, which cannot be processed correctly.
- In "examplefile2" on of the specimens has an empty specimenid, which is read as a number. The program expects specimenid to be a string, so it crashes

**Comment by mvences** [comment]
Thanks for checking. So in this case, since it is an obvious user mistake, there is no easy way to make the program "robust" against it. However it will be good to have an informative error message. Please for this and related problems, could you create a specific error message saying 
"Problem detected with specimenid values: There are either duplicated or missing values. The analysis could not be executed. Please correct the error(s) in the input file."
